ghostnet:
    onnx_file:     "../weights/ghostnet.onnx"
    engine_file:   "../weights/ghostnet.trt"
    labels_file:   "../configs/labels/imagenet.names"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   224
    IMAGE_HEIGHT:  224
    image_order:   "BCHW"
    channel_order: "BGR"
    img_mean:      [ 0.485, 0.456, 0.406 ]
    img_std:       [ 0.229, 0.224, 0.225 ]
    alpha:          255.0
    resize:         "directly"
