yolor:
    onnx_file:     "../weights/yolor-p6-paper-541.onnx"
    engine_file:   "../weights/yolor-p6-paper-541.trt"
    labels_file:   "../configs/labels/coco.names"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   1280
    IMAGE_HEIGHT:  1280
    image_order:   "BCHW"
    channel_order: "BGR"
    obj_threshold: 0.4
    nms_threshold: 0.45
    agnostic:      False
    strides:       [8, 16, 32, 64]
    num_anchors:   [3,  3,  3,  3]
    img_mean:      [ 0, 0, 0 ]
    img_std:       [ 1, 1, 1 ]
    alpha:         255.0
    resize:        "keep_ratio"
