arcface:
    onnx_file:     "../weights/arcface_r100.onnx"
    engine_file:   "../weights/arcface_r100.trt"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   112
    IMAGE_HEIGHT:  112
    image_order:   "BCHW"
    channel_order: "BGR"
    img_mean:      [ 0, 0, 0 ]
    img_std:       [ 1, 1, 1 ]
    alpha:         1.0
    resize:        "directly"
