face_alignment:
    onnx_file:     "../weights/2d106det.onnx"
    engine_file:   "../weights/2d106det.trt"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   192
    IMAGE_HEIGHT:  192
    image_order:   "BCHW"
    channel_order: "BGR"
    img_mean:      [ 0, 0, 0 ]
    img_std:       [ 1, 1, 1 ]
    alpha:         1.0
    resize:        "directly"
