MiniFASNet:
    onnx_file:     "../weights/2.7_80x80_MiniFASNetV2.onnx"
    engine_file:   "../weights/2.7_80x80_MiniFASNetV2.trt"
    labels_file:   "../configs/labels/antispoofing.names"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   80
    IMAGE_HEIGHT:  80
    image_order:   "BCHW"
    channel_order: "RGB"
    img_mean:      [ 0, 0, 0 ]
    img_std:       [ 1, 1, 1 ]
    alpha:         1.0
    resize:        "directly"
